server.port=8089

spring.application.name=ai-chat-service

spring.ai.chat.client.enabled=false
spring.ai.model.chat=none
spring.ai.model.embedding=none
spring.ai.model.image=none
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.moderation=none
