services:
  pgvector:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: pgvector-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_db